apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: front
spec:
  healthCheck:
    checkIntervalSec: 60
    timeoutSec: 60
    healthyThreshold: 1
    unhealthyThreshold: 5
    type: HTTP
    requestPath: /
    port: 8080