apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: documento
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 5
    type: HTTP
    requestPath: /actuator/health
    port: 8080